export enum UserRole { SUPER_ADMIN='super_admin', FINANCE='finance', ADMISSION='admission', TEACHER='teacher', STUDENT='student' }
export enum UserStatus { ACTIVE='active', INACTIVE='inactive', SUSPENDED='suspended', PENDING='pending' }
export enum FeeCategory { TUITION='tuition', ADMISSION='admission', EXAM='exam', LIBRARY='library', LABORATORY='laboratory', TRANSPORT='transport', HOSTEL='hostel', SPORTS='sports', UNIFORM='uniform', MISCELLANEOUS='miscellaneous', LATE_FEE='late_fee' }
export enum FeeFrequency { ONE_TIME='one_time', MONTHLY='monthly', QUARTERLY='quarterly', SEMI_ANNUAL='semi_annual', ANNUAL='annual', CUSTOM='custom' }
export enum InvoiceStatus { DRAFT='draft', ISSUED='issued', PARTIALLY_PAID='partially_paid', PAID='paid', OVERDUE='overdue', WAIVED='waived', CANCELLED='cancelled' }
export enum PaymentMethod { CASH='cash', BANK_TRANSFER='bank_transfer', CHEQUE='cheque', ONLINE='online', POS='pos' }
export enum PaymentStatus { PENDING='pending', COMPLETED='completed', FAILED='failed', REFUNDED='refunded', CANCELLED='cancelled' }
export enum WaiverStatus { PENDING='pending', APPROVED='approved', REJECTED='rejected' }
export enum DiscountType { PERCENTAGE='percentage', FIXED='fixed' }
export enum DiscountCategory { MERIT='merit', NEED_BASED='need_based', SIBLING='sibling', STAFF_WARD='staff_ward', SPECIAL='special' }
export enum AdmissionStatus { APPLIED='applied', UNDER_REVIEW='under_review', ADMITTED='admitted', REJECTED='rejected', WITHDRAWN='withdrawn' }

export interface ApiResponse<T> { success: boolean; message: string; data: T; timestamp: string; }
export interface PaginatedResult<T> { data: T[]; meta: { total: number; page: number; limit: number; totalPages: number; hasNextPage: boolean; hasPrevPage: boolean; }; }
export interface PaginationParams { page?: number; limit?: number; search?: string; sortBy?: string; sortOrder?: 'ASC'|'DESC'; }

export interface User { id: string; firstName: string; lastName: string; email: string; phone?: string; role: UserRole; status: UserStatus; gender?: string; dateOfBirth?: string; address?: string; avatarUrl?: string; employeeId?: string; department?: string; lastLogin?: string; emailVerified: boolean; isFirstLogin: boolean; createdAt: string; updatedAt: string; }
export interface AuthResponse { user: { id: string; email: string; firstName: string; lastName: string; role: UserRole; isFirstLogin: boolean; avatarUrl?: string; }; accessToken: string; refreshToken: string; }
export interface AcademicYear { id: string; name: string; startDate: string; endDate: string; isCurrent: boolean; description?: string; feeTarget: number; monthlyTargets?: Record<string,number>; quarterlyTargets?: Record<string,number>; createdAt: string; }
export interface SchoolClass { id: string; name: string; grade: string; section?: string; description?: string; maxCapacity: number; isActive: boolean; academicYearId: string; academicYear?: AcademicYear; classTeacherId?: string; classTeacher?: User; createdAt: string; }
export interface Student { id: string; userId: string; user?: User; registrationNumber: string; rollNumber?: string; classId?: string; class?: SchoolClass; academicYearId: string; academicYear?: AcademicYear; admissionDate?: string; admissionStatus: AdmissionStatus; fatherName?: string; fatherPhone?: string; fatherEmail?: string; motherName?: string; motherPhone?: string; guardianName?: string; guardianPhone?: string; hasSiblings: boolean; siblingDiscountEligible: boolean; isActive: boolean; transportRequired: boolean; hostelRequired: boolean; bloodGroup?: string; nationality?: string; notes?: string; createdAt: string; previousSchool?: string;  }
export interface FeeStructure { id: string; name: string; description?: string; category: FeeCategory; frequency: FeeFrequency; amount: number; academicYearId: string; academicYear?: AcademicYear; classId?: string; class?: SchoolClass; isMandatory: boolean; isActive: boolean; dueDayOfMonth?: number; dueDate?: string; lateFeeEnabled: boolean; lateFeeType?: DiscountType; lateFeeValue?: number; gracePeriodDays: number; sortOrder: number; createdAt: string; }
export interface Discount { id: string; name: string; description?: string; category: DiscountCategory; type: DiscountType; value: number; studentId?: string; student?: Student; feeStructureId?: string; feeStructure?: FeeStructure; academicYearId: string; validFrom?: string; validUntil?: string; isActive: boolean; approvedBy?: string; createdAt: string; }
export interface LineItem { feeStructureId: string; feeName: string; category: string; amount: number; discountAmount: number; netAmount: number; }
export interface FeeInvoice { id: string; invoiceNumber: string; studentId: string; student?: Student; academicYearId: string; academicYear?: AcademicYear; billingMonth?: number; billingYear?: number; billingQuarter?: number; billingLabel?: string; issueDate: string; dueDate: string; status: InvoiceStatus; subtotal: number; discountAmount: number; lateFeeAmount: number; totalAmount: number; paidAmount: number; balanceAmount: number; waivedAmount: number; lineItems: LineItem[]; notes?: string; reminderCount: number; lastReminderAt?: string; createdAt: string; }
export interface FeeWaiver { id: string; invoiceId: string; invoice?: FeeInvoice; studentId: string; student?: Student; type: DiscountType; value: number; waivedAmount: number; reason: string; status: WaiverStatus; requestedBy?: string; reviewedBy?: string; reviewedAt?: string; reviewRemarks?: string; createdAt: string; }
export interface Payment { id: string; receiptNumber: string; invoiceId: string; invoice?: FeeInvoice; studentId: string; student?: Student; amount: number; method: PaymentMethod; status: PaymentStatus; paymentDate: string; transactionId?: string; bankName?: string; chequeNumber?: string; chequeDate?: string; remarks?: string; isRefunded: boolean; refundedAmount?: number; collectedBy?: string; verifiedBy?: string; verifiedAt?: string; createdAt: string; }

export interface DashboardSummary { summary: { totalStudents:number; totalInvoiced:number; totalCollected:number; totalOutstanding:number; overdueAmount:number; totalWaived:number; defaulterCount:number; collectionRate:string; }; charts: { monthlyTrend:MonthlyTrend[]; classWiseSummary:ClassWiseSummary[]; paymentMethodBreakdown:PaymentMethodData[]; }; recentPayments:Payment[]; }
export interface MonthlyTrend { month:number; year:number; monthName:string; collected:number; }
export interface ClassWiseSummary { className:string; grade:string; collected:string; outstanding:string; }
export interface PaymentMethodData { method:string; amount:string; count:string; }
export interface TargetVsActual { academicYear:string; annual:{target:number;collected:number;shortfall:number;achievementRate:string;}; quarterly:QuarterlyData[]; monthly:MonthlyData[]; }
export interface MonthlyData { month:number; monthName:string; target:number; invoiced:number; collected:number; shortfall:number; surplus:number; achievementRate:string; }
export interface QuarterlyData { quarter:string; months:string; target:number; invoiced:number; collected:number; shortfall:number; achievementRate:string; }
export interface Defaulter { studentId:string; registrationNumber:string; firstName:string; lastName:string; email:string; fatherPhone?:string; fatherName?:string; className:string; grade:string; totalDue:number; totalBilled:number; totalPaid:number; pendingInvoices:number; oldestDueDate:string; }
